"""
ADOFAI inference and export functionality.

This module provides stub/placeholder inference for ADOFAI format, demonstrating
the export pipeline. Quality ADOFAI generation requires model retraining on ADOFAI data.
"""

from __future__ import annotations
from pathlib import Path
import random
from typing import Optional

from .parser import AdofaiLevel, write_adofai
from .event import AdofaiEvent, AdofaiEventType
from .converter import AdofaiConverter


def create_stub_adofai(
    output_path: str | Path,
    audio_filename: str = "song.ogg",
    bpm: float = 120,
    offset: int = 0,
    title: str = "Generated Song",
    artist: str = "Unknown Artist",
    creator: str = "Mapperatorinator ADOFAI",
    duration_ms: Optional[float] = None,
) -> Path:
    """
    Create a stub/placeholder ADOFAI file with basic structure.
    
    This demonstrates the export pipeline. For quality charts, retrain the model
    on ADOFAI dataset.
    
    Args:
        output_path: Directory to write .adofai file
        audio_filename: Name of audio file
        bpm: Beats per minute
        offset: Timing offset in ms
        title: Song title
        artist: Artist name
        creator: Chart creator name
        duration_ms: Optional song duration for generating appropriate length
        
    Returns:
        Path to created .adofai file
    """
    output_path = Path(output_path)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Generate a simple pattern as placeholder
    # In a real implementation, this would come from the model
    angle_data = generate_placeholder_pattern(bpm, duration_ms or 30000)
    
    # Create minimal actions
    actions = [
        {
            "floor": 1,
            "eventType": "SetSpeed",
            "speedType": "Bpm",
            "beatsPerMinute": bpm,
            "bpmMultiplier": 1.0
        }
    ]
    
    # Add some variety to demonstrate action support
    if len(angle_data) > 10:
        actions.append({
            "floor": len(angle_data) // 3,
            "eventType": "Twirl"
        })
    
    if len(angle_data) > 20:
        actions.append({
            "floor": len(angle_data) // 2,
            "eventType": "SetSpeed",
            "speedType": "Multiplier",
            "beatsPerMinute": bpm,
            "bpmMultiplier": 1.2
        })
    
    # Create settings
    settings = {
        "version": 14,
        "artist": artist,
        "song": title,
        "author": creator,
        "separateCountdownTime": True,
        "previewSongStart": 0,
        "previewSongDuration": 10,
        "seizureWarning": False,
        "levelDesc": "Generated by Mapperatorinator ADOFAI (stub generation - model retraining needed for quality)",
        "levelTags": "ai-generated",
        "artistPermission": "",
        "songFilename": audio_filename,
        "bpm": bpm,
        "volume": 100,
        "offset": offset,
        "pitch": 100,
        "hitsound": "Kick",
        "hitsoundVolume": 100,
    }
    
    level = AdofaiLevel(
        settings=settings,
        angle_data=angle_data,
        actions=actions,
        decorations=[]
    )
    
    # Write to file
    output_file = output_path / f"{title.replace(' ', '_')}.adofai"
    write_adofai(level, output_file)
    
    return output_file


def generate_placeholder_pattern(bpm: float, duration_ms: float) -> list[int]:
    """
    Generate a placeholder angle pattern for demonstration.
    
    This is NOT a trained model output - just a playable placeholder pattern
    to demonstrate the export format.
    
    Args:
        bpm: Beats per minute
        duration_ms: Duration in milliseconds
        
    Returns:
        List of tile angles
    """
    # Calculate approximate number of tiles based on duration
    # Assume average ~180 degree rotation per tile (1 beat per tile)
    ms_per_beat = 60000 / bpm
    num_tiles = max(10, int(duration_ms / ms_per_beat))
    
    # Generate a simple but varied pattern
    # Use common angles: 0, 45, 90, 135, 180, 225, 270, 315
    common_angles = [0, 45, 90, 135, 180, 225, 270, 315]
    
    angles = []
    for i in range(num_tiles):
        # Create some structure: mostly straight/90° turns with occasional 45° angles
        if i % 8 == 0:
            # Occasional 45° angles
            angle = random.choice([45, 135, 225, 315])
        elif i % 4 == 0:
            # Regular 90° turns
            angle = random.choice([0, 90, 180, 270])
        else:
            # Mostly continue in similar direction
            if angles:
                # Slight variation from previous
                prev = angles[-1]
                angle = random.choice([
                    prev,
                    (prev + 90) % 360,
                    (prev - 90) % 360
                ])
            else:
                angle = 0
        
        angles.append(angle)
    
    # Add an occasional midspin for variety
    if len(angles) > 20:
        midspin_pos = len(angles) // 2
        angles.insert(midspin_pos, 999)
    
    return angles


def export_adofai_from_events(
    events: list[AdofaiEvent],
    event_times: list[float],
    output_path: str | Path,
    audio_filename: str = "song.ogg",
    title: str = "Generated Song",
    artist: str = "Unknown Artist",
    creator: str = "Mapperatorinator ADOFAI",
) -> Path:
    """
    Export ADOFAI file from event sequence (from model inference).
    
    This is the main export function to use when model generates events.
    
    Args:
        events: List of AdofaiEvent objects from model
        event_times: List of timestamps for events
        output_path: Directory to write .adofai file
        audio_filename: Name of audio file
        title: Song title
        artist: Artist name
        creator: Chart creator name
        
    Returns:
        Path to created .adofai file
    """
    output_path = Path(output_path)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Convert events to level structure
    converter = AdofaiConverter()
    
    base_settings = {
        "artist": artist,
        "song": title,
        "author": creator,
        "songFilename": audio_filename,
    }
    
    level = converter.events_to_level(events, event_times, base_settings)
    
    # Write to file
    output_file = output_path / f"{title.replace(' ', '_')}.adofai"
    write_adofai(level, output_file)
    
    return output_file
