from __future__ import annotations

import dataclasses
from enum import Enum


class EventType(Enum):
    TIME_SHIFT = "t"
    SNAPPING = "snap"
    DISTANCE = "dist"
    NEW_COMBO = "new_combo"
    HITSOUND = "hitsound"
    VOLUME = "volume"
    CIRCLE = "circle"
    SPINNER = "spinner"
    SPINNER_END = "spinner_end"
    SLIDER_HEAD = "slider_head"
    BEZIER_ANCHOR = "bezier_anchor"
    PERFECT_ANCHOR = "perfect_anchor"
    CATMULL_ANCHOR = "catmull_anchor"
    RED_ANCHOR = "red_anchor"
    LAST_ANCHOR = "last_anchor"
    SLIDER_END = "slider_end"
    BEAT = "beat"
    MEASURE = "measure"
    TIMING_POINT = "timing_point"
    GAMEMODE = "gamemode"
    STYLE = "style"
    DIFFICULTY = "difficulty"
    MAPPER = "mapper"
    CS = "cs"
    YEAR = "year"
    HITSOUNDED = "hitsounded"
    SONG_LENGTH = "song_length"
    SONG_POSITION = "song_position"
    GLOBAL_SV = "global_sv"
    MANIA_KEYCOUNT = "keycount"
    HOLD_NOTE_RATIO = "hold_note_ratio"
    SCROLL_SPEED_RATIO = "scroll_speed_ratio"
    DESCRIPTOR = "descriptor"
    POS_X = "pos_x"
    POS_Y = "pos_y"
    POS = "pos"
    KIAI = "kiai"
    MANIA_COLUMN = "column"
    HOLD_NOTE = "hold_note"
    HOLD_NOTE_END = "hold_note_end"
    SCROLL_SPEED_CHANGE = "scroll_speed_change"
    SCROLL_SPEED = "scroll_speed"
    DRUMROLL = "drumroll"
    DRUMROLL_END = "drumroll_end"
    DENDEN = "denden"
    DENDEN_END = "denden_end"
    CONTROL = "control"
    SLIDER_SUSTAIN = "slider_sustain"
    SLIDER_REPEAT_SUSTAIN = "slider_repeat_sustain"
    SPINNER_SUSTAIN = "spinner_sustain"
    HOLD_NOTE_SUSTAIN = "hold_note_sustain"
    DRUMROLL_SUSTAIN = "drumroll_sustain"
    DENDEN_SUSTAIN = "denden_sustain"
    POS_REFINE = "pos_refine"

    # ADOFAI event types
    TILE_ANGLE = "adofai_angle"
    MIDSPIN = "adofai_midspin"
    SET_SPEED_BPM = "adofai_speed_bpm"
    SET_SPEED_MULT = "adofai_speed_mult"
    PAUSE = "adofai_pause"
    HOLD = "adofai_hold"
    TWIRL = "adofai_twirl"
    MULTI_PLANET = "adofai_multiplanet"
    CHECKPOINT = "adofai_checkpoint"
    AUTO_PLAY_TILES = "adofai_autoplay"
    SET_PLANET_ROTATION = "adofai_planet_rot"
    FREE_ROAM = "adofai_freeroam"
    FREE_ROAM_TWIRL = "adofai_freeroam_twirl"
    FREE_ROAM_REMOVE = "adofai_freeroam_remove"
    SCALE_MARGIN = "adofai_scale_margin"
    SCALE_RADIUS = "adofai_scale_radius"
    MULTITAP = "adofai_multitap"
    HIDE = "adofai_hide"
    KILL_PLAYER = "adofai_kill_player"
    POSITION_TRACK = "adofai_pos_track"
    MOVE_TRACK = "adofai_move_track"
    COLOR_TRACK = "adofai_color_track"
    ANIMATE_TRACK = "adofai_anim_track"
    MOVE_CAMERA = "adofai_move_camera"
    CAMERA_POSITION_X = "adofai_cam_x"
    CAMERA_POSITION_Y = "adofai_cam_y"
    CAMERA_ROTATION = "adofai_cam_rot"
    CAMERA_ZOOM = "adofai_cam_zoom"
    CAMERA_DURATION = "adofai_cam_dur"
    CAMERA_EASE = "adofai_cam_ease"
    CAMERA_RELATIVE = "adofai_cam_rel"
    SET_HITSOUND = "adofai_set_hitsound"
    PLAY_SOUND = "adofai_play_sound"
    SET_HOLD_SOUND = "adofai_set_hold_sound"
    REPEAT_EVENTS = "adofai_repeat_events"
    SET_CONDITIONAL_EVENTS = "adofai_set_cond"
    SET_INPUT_EVENT = "adofai_set_input"
    FLASH = "adofai_flash"
    BLOOM = "adofai_bloom"
    SHAKE_SCREEN = "adofai_shake_screen"
    SET_FILTER = "adofai_set_filter"
    SET_FILTER_ADVANCED = "adofai_set_filter_adv"
    FILTER_PROPERTIES = "adofai_filter_props"
    BOOKMARK = "adofai_bookmark"
    EDITOR_COMMENT = "adofai_editor_comment"
    CALL_METHOD = "adofai_call_method"
    ADD_COMPONENT = "adofai_add_component"
    CHANGE_TRACK = "adofai_change_track"
    FREE_ROAM_WARNING = "adofai_freeroam_warn"
    PAUSE_COUNTDOWN = "adofai_pause_ticks"
    PAUSE_ANGLE_DIR = "adofai_pause_dir"
    HOLD_DISTANCE = "adofai_hold_dist"
    HOLD_LANDING = "adofai_hold_land"
    TRACK_START_TILE = "adofai_track_start"
    TRACK_END_TILE = "adofai_track_end"
    VFX_PLANE = "adofai_vfx_plane"
    VFX_COLOR = "adofai_vfx_color"
    VFX_OPACITY = "adofai_vfx_opacity"
    VFX_ENABLED = "adofai_vfx_enabled"
    VFX_DISABLE_OTHERS = "adofai_vfx_disable_others"
    VFX_INTENSITY = "adofai_vfx_intensity"
    VFX_STRENGTH = "adofai_vfx_strength"
    VFX_THRESHOLD = "adofai_vfx_threshold"
    ANGLE_OFFSET = "adofai_angle_offset"
    PITCH = "adofai_pitch"
    BPM = "adofai_bpm"
    OFFSET = "adofai_offset"


class ContextType(Enum):
    NONE = "none"
    TIMING = "timing"
    NO_HS = "no_hs"
    GD = "gd"
    MAP = "map"
    KIAI = "kiai"
    SV = "sv"


@dataclasses.dataclass
class EventRange:
    type: EventType
    min_value: int
    max_value: int


@dataclasses.dataclass
class Event:
    type: EventType
    value: int = 0

    def __repr__(self) -> str:
        return f"{self.type.value}{self.value}"

    def __str__(self) -> str:
        return f"{self.type.value}{self.value}"
